import type { Locator, Page } from "@playwright/test";

/**
 * Component-level Page Object for the auth popup that opens from the
 * landing page. Owns its own selectors so a spec never reaches into the
 * popup's internal DOM directly.
 */
export class AuthPopup {
  private readonly page: Page;
  readonly container: Locator;
  readonly modeSwitch: Locator;
  readonly closeButton: Locator;
  /** Present only when the popup is in sign-in mode (current-password input). */
  readonly signInForm: Locator;
  /** Present only when the popup is in sign-up mode (new-password input). */
  readonly signUpForm: Locator;

  constructor(page: Page) {
    this.page = page;
    // `.auth-panel-popup` is generated by AuthPanel.tsx via cn("auth-panel", `auth-panel-${variant}`).
    this.container = page.locator(".auth-panel-popup");
    this.modeSwitch = this.container.locator(".auth-mode-switch");
    this.closeButton = this.container.locator(".auth-close");
    this.signInForm = this.container.locator(
      'input[autocomplete="current-password"]',
    );
    this.signUpForm = this.container
      .locator('input[autocomplete="new-password"]')
      .first();
  }

  async clickModeSwitch(): Promise<void> {
    await this.modeSwitch.click();
  }

  async close(): Promise<void> {
    await this.closeButton.click();
  }
}
