import type { Locator, Page } from "@playwright/test";

/**
 * Component-level Page Object for the auth popup that opens from the
 * landing page. Owns its own selectors so a spec never reaches into the
 * popup's internal DOM directly.
 */
export class AuthPopup {
  private readonly page: Page;
  readonly container: Locator;
  readonly panelTitle: Locator;
  readonly modeSwitch: Locator;
  readonly closeButton: Locator;
  /** "Continue with Google" social button (spec 037; leads the form since 048). */
  readonly googleButton: Locator;
  /** Email input of whichever email-bearing form is active. */
  readonly emailInput: Locator;
  /** Every input of the active form (sign-up renders exactly 3, spec 048). */
  readonly formInputs: Locator;
  /** Present only when the popup is in sign-in mode (current-password input). */
  readonly signInForm: Locator;
  /** Present only when the popup is in sign-up mode (new-password input). */
  readonly signUpForm: Locator;
  /** "Forgot password?" affordance shown in sign-in mode (spec 035). */
  readonly forgotPasswordLink: Locator;
  /** Recovery step 1: email entry (spec 035). */
  readonly recoveryEmailInput: Locator;
  /** Recovery step 2: emailed one-time code entry (spec 035). */
  readonly recoveryCodeInput: Locator;
  readonly recoveryNewPasswordInput: Locator;
  readonly recoveryConfirmPasswordInput: Locator;
  /** Submit button of whichever recovery step is active. */
  readonly recoverySubmit: Locator;
  /** "Resend code" affordance on the recovery completion step. */
  readonly recoveryResend: Locator;
  /** Server-reported message area shared by every auth mode. */
  readonly serverMessage: Locator;
  /** Consent link must always target the Terms that currently govern signup. */
  readonly termsLink: Locator;

  constructor(page: Page) {
    this.page = page;
    // `.auth-panel-popup` is generated by AuthPanel.tsx via cn("auth-panel", `auth-panel-${variant}`).
    this.container = page.locator(".auth-panel-popup");
    this.panelTitle = this.container.locator(".auth-panel-title");
    // The sign-in↔sign-up switch link under the active form (spec 048; the
    // former header mode-switch button is gone).
    this.modeSwitch = this.container.getByTestId("auth-mode-switch");
    this.closeButton = this.container.locator(".auth-close");
    this.googleButton = this.container.getByTestId("auth-google-button");
    this.emailInput = this.container.locator('input[name="email"]');
    this.formInputs = this.container.locator("form input");
    this.signInForm = this.container.locator(
      'input[autocomplete="current-password"]',
    );
    this.signUpForm = this.container
      .locator('input[autocomplete="new-password"]')
      .first();
    this.forgotPasswordLink = this.container.getByTestId("auth-forgot-link");
    this.recoveryEmailInput = this.container.getByTestId(
      "recovery-email-input",
    );
    this.recoveryCodeInput = this.container.getByTestId("recovery-code-input");
    this.recoveryNewPasswordInput = this.container.getByTestId(
      "recovery-new-password-input",
    );
    this.recoveryConfirmPasswordInput = this.container.getByTestId(
      "recovery-confirm-password-input",
    );
    this.recoverySubmit = this.container.getByTestId("recovery-submit");
    this.recoveryResend = this.container.getByTestId("recovery-resend");
    this.serverMessage = this.container.locator(".auth-server-message");
    this.termsLink = this.container.locator('.auth-terms-note a[href*="terms-of-use"]');
  }

  async clickModeSwitch(): Promise<void> {
    await this.modeSwitch.click();
  }

  async close(): Promise<void> {
    await this.closeButton.click();
  }

  /** Submit the sign-in form (popup must be in sign-in mode). */
  async signIn(email: string, password: string): Promise<void> {
    await this.emailInput.fill(email);
    await this.container.locator('input[name="password"]').fill(password);
    await this.container.locator('button[type="submit"]').click();
  }

  /** Switch to sign-up mode and register an account (credentials only,
   * spec 048 — profile details move to the profile screen). */
  async signUp(email: string, password: string): Promise<void> {
    await this.clickModeSwitch();
    await this.emailInput.fill(email);
    await this.container.locator('input[name="password"]').fill(password);
    await this.container
      .locator('input[name="confirmPassword"]')
      .fill(password);
    await this.container.locator('button[type="submit"]').click();
  }

  /** Open recovery mode and request a code for the given email. */
  async requestRecovery(email: string): Promise<void> {
    await this.forgotPasswordLink.click();
    await this.recoveryEmailInput.fill(email);
    await this.recoverySubmit.click();
  }

  /** Complete recovery with the emailed code and a new password. */
  async completeRecovery(code: string, newPassword: string): Promise<void> {
    await this.recoveryCodeInput.fill(code);
    await this.recoveryNewPasswordInput.fill(newPassword);
    await this.recoveryConfirmPasswordInput.fill(newPassword);
    await this.recoverySubmit.click();
  }
}
